name: "Run OPA with conftest"
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to check out the code from the repo
  pull-requests: write # allow GH Action to write in the PR

# Pipeline must run only changes/addition to terraform files and PR to main branch
on:
  pull_request:
    branches:
      - main
jobs:
  inform_about_tests:
    name: Conftest notification
    runs-on: ubuntu-22.04
    steps:
      - name: Inform on OPA testing
        id: inform_pr
        uses: marocchino/sticky-pull-request-comment@v2.1.0
        with:
          header: Will Run OPA/Conftest
          message: |
            ***Running conftest test on ${{ github.sha }}***
            ***Tests are located in /policy***
            Results will display below momentarily...
            If test pass merging will be allowed.
            If they do not pass you will need to resolve the issue and commit it back.
            Documentation: TBA

  runs-conftest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Conftest
        id: setup_conftest
        uses: princespaghetti/setup-conftest@v1
        with:
          version: 0.32.x

      - name: Setup hcl2json
        run: |
          wget -O ./hcl2json https://github.com/tmccombs/hcl2json/releases/download/v0.3.4/hcl2json_linux_amd64 -q
          chmod 755 ./hcl2json

          terraform:
           - name: 'Terraform'
       # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
              cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}